// DevOps envelope generation (TRD §7): for a workspace, the backend emits a
// standardized runtime — docker-compose.yml, a .devcontainer, and starter
// project files — that the local `nodecode-runner` writes to disk and boots.
// Pure string generation; no Docker or filesystem access here.

export interface EnvelopeFile {
  path: string;
  content: string;
}

export type DatabaseKind = "postgres" | "redis" | "none";

/** Heuristic: infer a datastore need from the project's source text. */
export function inferDatabase(sources: string[]): DatabaseKind {
  const blob = sources.join("\n").toLowerCase();
  if (/\b(pg|postgres|prisma|drizzle|typeorm|sequelize)\b/.test(blob)) return "postgres";
  if (/\bredis|ioredis\b/.test(blob)) return "redis";
  return "none";
}

function dockerCompose(database: DatabaseKind): string {
  const dbService =
    database === "postgres"
      ? `
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - "5434:5432"
    volumes:
      - db-data:/var/lib/postgresql/data`
      : database === "redis"
        ? `
  db:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"`
        : "";

  const dependsOn = database === "none" ? "" : `
    depends_on:
      - db`;
  const volumes = database === "postgres" ? `\nvolumes:\n  db-data:\n` : "\n";

  return `# Generated by NodeCode (TRD §7). Boot: docker compose up --build
services:
  app:
    build: .
    restart: unless-stopped
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules${dependsOn}${dbService}
${volumes}`;
}

function dockerfile(): string {
  return `# Generated by NodeCode
FROM node:22-alpine
WORKDIR /app
COPY package.json ./
RUN npm install
COPY . .
EXPOSE 8080
CMD ["npm", "run", "dev"]
`;
}

function devcontainer(projectName: string): string {
  return JSON.stringify(
    {
      name: projectName,
      dockerComposeFile: "../docker-compose.yml",
      service: "app",
      workspaceFolder: "/app",
      customizations: {
        vscode: {
          extensions: ["dbaeumer.vscode-eslint", "esbenp.prettier-vscode"],
        },
      },
    },
    null,
    2,
  );
}

function packageJson(projectName: string): string {
  return JSON.stringify(
    {
      name: projectName || "nodecode-project",
      private: true,
      type: "module",
      scripts: {
        dev: "tsx watch src/index.ts",
        start: "tsx src/index.ts",
      },
      dependencies: {},
      devDependencies: { tsx: "^4.19.0", typescript: "^5" },
    },
    null,
    2,
  );
}

function tsconfig(): string {
  return JSON.stringify(
    {
      compilerOptions: {
        target: "ES2022",
        module: "ESNext",
        moduleResolution: "bundler",
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
        outDir: "dist",
      },
      include: ["src"],
    },
    null,
    2,
  );
}

/**
 * Builds the full runtime envelope for a workspace. `entryFiles` are the actual
 * code modules (filePath + source) that ship alongside the generated scaffold.
 */
export function buildEnvelope(options: {
  projectName: string;
  database: DatabaseKind;
}): EnvelopeFile[] {
  const { projectName, database } = options;
  return [
    { path: "docker-compose.yml", content: dockerCompose(database) },
    { path: "Dockerfile", content: dockerfile() },
    { path: ".devcontainer/devcontainer.json", content: devcontainer(projectName) },
    { path: "package.json", content: packageJson(projectName) },
    { path: "tsconfig.json", content: tsconfig() },
    {
      path: ".dockerignore",
      content: "node_modules\ndist\n.git\n",
    },
  ];
}
